#!/bin/bash
#set -ex
set -e
#create variables for user & group
if ! source ./users.cfg 2>/dev/null; then
	echo "ERROR: file 'users.cfg' not found! Aborting."
	exit 1 #script is aborting
fi


echo "=== Creating IAM Ressources ==="
echo "working with user: ${USER_NAME}"
echo "working with group: ${USER_GROUP}"
echo


#create aws user if doesn't exists, take name from users.cfg
if aws iam create-user --user-name "${USER_NAME}" 2>/dev/null; then
	echo "user with this name already exists"
else 
	echo "user ${USER_NAME} is created"
fi

:<< 'TODO'
error from terminal (15.02.2026)
+ aws iam create-group --group-name practice-dev-group-1

An error occurred (EntityAlreadyExists) when calling the CreateGroup operation: Group with name practice-dev-group-1 already exists


need to add check for existing group
TODO

#create aws group if doesn't exists, take name from users.cfg
if aws iam create-group --group-name "${USER_GROUP}" 2>/dev/null; then
       echo "group with this name alread exists"
else
 	echo "creating group ${USER_GROUP}"
fi

echo 
echo "=== add user to group ==="
echo "no need to check, if user is already in group. add-user-to-group works idempotent"
echo "add user:${USER_NAME} to group:${USER_GROUP}"
aws iam add-user-to-group --user-name "${USER_NAME}" --group-name "${USER_GROUP}"
echo

echo "=== remove user from group ==="
echo "no need to check, if user is already removed from the group, it works idemppotent"
echo "remove user: ${USER_NAME} from group:${USER_GROUP}"
aws iam remove-user-from-group --user-name "${USER_NAME}" --group-name "${USER_GROUP}"
echo


echo "=== delete user and group ==="
echo "step 1: delete user, here i need to check, if user exists. Delete-operation is not idempotent"
if aws iam delete-user --user-name "${USER_NAME}" 2>/dev/null; then
	echo "user is not extist"
else	
	echo "user ${USER_NAME} is deleted"
fi
echo

echo "step 2: delete group, also need to check, if group exists, but also, if it's not empty"





